//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunnersTrackerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityTypes
    {
        public ActivityTypes()
        {
            this.LogEntries = new HashSet<LogEntry>();
        }
    
        public int Id { get; set; }
        public string ActivityType_Name { get; set; }
    
        public virtual ICollection<LogEntry> LogEntries { get; set; }
    }
}
