//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunnersTrackerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEntry
    {
        public int LogId { get; set; }
        public string ActivityName { get; set; }
        public string ActivityType { get; set; }
        public System.DateTime StartTime { get; set; }
        public string TimeZone { get; set; }
        public int Duration { get; set; }
        public decimal Distance { get; set; }
        public Nullable<int> Calories { get; set; }
        public string Description { get; set; }
        public string Tags { get; set; }
        public int ShoeShoeId { get; set; }
        public int UserUserId { get; set; }
    
        public virtual Shoe Shoe { get; set; }
        public virtual User User { get; set; }
    }
}
