//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunnersTrackerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shoe
    {
        public Shoe()
        {
            this.ShoeDistance = 0m;
            this.LogEntries = new HashSet<LogEntry>();
        }
    
        public int ShoeId { get; set; }
        public string ShoeName { get; set; }
        public decimal ShoeDistance { get; set; }
        public int ShoeUserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<LogEntry> LogEntries { get; set; }
    }
}
