//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunnersTrackerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.DistanceType = "Miles";
            this.AccountConfirmed = false;
            this.Shoes = new HashSet<Shoe>();
            this.LogEntries = new HashSet<LogEntry>();
        }
    
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string TimeZone { get; set; }
        public string DistanceType { get; set; }
        public bool AccountConfirmed { get; set; }
        public string ConfirmCode { get; set; }
        public string PassResetCode { get; set; }
        public Nullable<System.DateTime> PassResetExpire { get; set; }
    
        public virtual ICollection<Shoe> Shoes { get; set; }
        public virtual ICollection<LogEntry> LogEntries { get; set; }
    }
}
