//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/03/20 - 16:58:01
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace RunnersTracker.Business.DTO
{
    [DataContract()]
    public partial class ActivityTypesDTO
    {
        [DataMember()]
        public Int32 Id { get; set; }

        [DataMember()]
        public String ActivityType_Name { get; set; }

        [DataMember()]
        public List<Int32> LogEntries_LogId { get; set; }

        public ActivityTypesDTO()
        {
        }

        public ActivityTypesDTO(Int32 id, String activityType_Name, List<Int32> logEntries_LogId)
        {
			this.Id = id;
			this.ActivityType_Name = activityType_Name;
			this.LogEntries_LogId = logEntries_LogId;
        }
    }
}
