//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/03/20 - 16:58:00
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace RunnersTracker.Business.DTO
{
    [DataContract()]
    public partial class LogEntryDTO
    {
        [DataMember()]
        public Int32 LogId { get; set; }

        [DataMember()]
        public String ActivityName { get; set; }

        [DataMember()]
        public DateTime StartTime { get; set; }

        [DataMember()]
        public String TimeZone { get; set; }

        [DataMember()]
        public Int32 Duration { get; set; }

        [DataMember()]
        public Decimal Distance { get; set; }

        [DataMember()]
        public Nullable<Int32> Calories { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public String Tags { get; set; }

        [DataMember()]
        public Int32 ShoeShoeId { get; set; }

        [DataMember()]
        public Int32 UserUserId { get; set; }

        [DataMember()]
        public Int32 Shoe_ShoeId { get; set; }

        [DataMember()]
        public Int32 User_UserId { get; set; }

        [DataMember()]
        public Int32 ActivityType_Id { get; set; }

        public LogEntryDTO()
        {
        }

        public LogEntryDTO(Int32 logId, String activityName, DateTime startTime, String timeZone, Int32 duration, Decimal distance, Nullable<Int32> calories, String description, String tags, Int32 shoeShoeId, Int32 userUserId, Int32 shoe_ShoeId, Int32 user_UserId, Int32 activityType_Id)
        {
			this.LogId = logId;
			this.ActivityName = activityName;
			this.StartTime = startTime;
			this.TimeZone = timeZone;
			this.Duration = duration;
			this.Distance = distance;
			this.Calories = calories;
			this.Description = description;
			this.Tags = tags;
			this.ShoeShoeId = shoeShoeId;
			this.UserUserId = userUserId;
			this.Shoe_ShoeId = shoe_ShoeId;
			this.User_UserId = user_UserId;
			this.ActivityType_Id = activityType_Id;
        }
    }
}
