//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/03/08 - 14:06:41
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Business.DTO
{
    [DataContract()]
    public partial class ShoeDTO
    {
        [DataMember()]
        public Int32 ShoeId { get; set; }

        [DataMember()]
        public String ShoeName { get; set; }

        [DataMember()]
        public Decimal ShoeDistance { get; set; }

        [DataMember()]
        public Int32 ShoeUserId { get; set; }

        [DataMember()]
        public Int32 User_UserId { get; set; }

        [DataMember()]
        public List<Int32> LogEntries_LogId { get; set; }

        public ShoeDTO()
        {
        }

        public ShoeDTO(Int32 shoeId, String shoeName, Decimal shoeDistance, Int32 shoeUserId, Int32 user_UserId, List<Int32> logEntries_LogId)
        {
			this.ShoeId = shoeId;
			this.ShoeName = shoeName;
			this.ShoeDistance = shoeDistance;
			this.ShoeUserId = shoeUserId;
			this.User_UserId = user_UserId;
			this.LogEntries_LogId = logEntries_LogId;
        }
    }
}
