//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/03/25 - 16:17:35
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace RunnersTracker.Business.DTO
{
    [DataContract()]
    public partial class ShoeDTO
    {
        [DataMember()]
        public Int32 ShoeId { get; set; }

        [DataMember()]
        public String ShoeName { get; set; }

        [DataMember()]
        public Decimal ShoeDistance { get; set; }

        [DataMember()]
        public Int32 ShoeUserId { get; set; }

        [DataMember()]
        public String ShoeBrand { get; set; }

        [DataMember()]
        public String ShoeModel { get; set; }

        [DataMember()]
        public DateTime PurchaseDate { get; set; }

        [DataMember()]
        public Int32 UserId { get; set; }

        [DataMember()]
        public List<Int32> LogEntries_LogId { get; set; }

        [DataMember()]
        public Int32 User_UserId { get; set; }

        public ShoeDTO()
        {
        }

        public ShoeDTO(Int32 shoeId, String shoeName, Decimal shoeDistance, Int32 shoeUserId, String shoeBrand, String shoeModel, DateTime purchaseDate, Int32 userId, List<Int32> logEntries_LogId, Int32 user_UserId)
        {
			this.ShoeId = shoeId;
			this.ShoeName = shoeName;
			this.ShoeDistance = shoeDistance;
			this.ShoeUserId = shoeUserId;
			this.ShoeBrand = shoeBrand;
			this.ShoeModel = shoeModel;
			this.PurchaseDate = purchaseDate;
			this.UserId = userId;
			this.LogEntries_LogId = logEntries_LogId;
			this.User_UserId = user_UserId;
        }
    }
}
