//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/03/12 - 12:50:05
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace RunnersTracker.Business.DTO
{
    [DataContract()]
    public partial class UserDTO
    {
        [DataMember()]
        public Int32 UserId { get; set; }

        [DataMember()]
        public String FirstName { get; set; }

        [DataMember()]
        public String LastName { get; set; }

        [DataMember()]
        public String Email { get; set; }

        [DataMember()]
        public Byte[] Password { get; set; }

        [DataMember()]
        public String TimeZone { get; set; }

        [DataMember()]
        public String DistanceType { get; set; }

        [DataMember()]
        public Boolean AccountConfirmed { get; set; }

        [DataMember()]
        public String ConfirmCode { get; set; }

        [DataMember()]
        public String PassResetCode { get; set; }

        [DataMember()]
        public Nullable<DateTime> PassResetExpire { get; set; }

        [DataMember()]
        public Byte[] Salt { get; set; }

        [DataMember()]
        public List<Int32> Shoes_ShoeId { get; set; }

        [DataMember()]
        public List<Int32> LogEntries_LogId { get; set; }

        public UserDTO()
        {
        }

        public UserDTO(Int32 userId, String firstName, String lastName, String email, Byte[] password, String timeZone, String distanceType, Boolean accountConfirmed, String confirmCode, String passResetCode, Nullable<DateTime> passResetExpire, Byte[] salt, List<Int32> shoes_ShoeId, List<Int32> logEntries_LogId)
        {
			this.UserId = userId;
			this.FirstName = firstName;
			this.LastName = lastName;
			this.Email = email;
			this.Password = password;
			this.TimeZone = timeZone;
			this.DistanceType = distanceType;
			this.AccountConfirmed = accountConfirmed;
			this.ConfirmCode = confirmCode;
			this.PassResetCode = passResetCode;
			this.PassResetExpire = passResetExpire;
			this.Salt = salt;
			this.Shoes_ShoeId = shoes_ShoeId;
			this.LogEntries_LogId = logEntries_LogId;
        }
    }
}
